### ISSUE TITLE
CS-TML-4 : Добавить адаптивность элементам макета от блока "Call-in Technician" до блока "Results"

### ISSUE THREAD

**Issue by Orangetime** [school-winter-2020/school-winter-2020.github.io#31]

**Comment by rualt** [comment]
Пересмотрел этот блок, он уже адаптивный, делали его пополам с Андреем А.
Margin left/right 20 для элементов тоже уже установлены.
Для этого блока https://prnt.sc/rblrdp боковые маржины пропали, т.к. Богдан обернул их в свой контейнер, не стал править. 

Короч вроде все норм.
